---
- name: 'Install packages'
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpie
    - haproxy

- name: 'Configure haproxy'
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: enable and start haproxy

- name: 'Start haproxy'
  service:
    name: haproxy
    enabled: yes
    state: started
    
